name: "cmake-build-and-test"
description: "Run CMake with CMakePreset.json to configure, build and test C/C++ source code."

runs:
  using: "composite"
  steps:
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

    # TODO move into separate action? ideally into a JS action "post" that setup ccache?
    - name: Print ccache/sccache stats
      # display stats even if tests failed
      if: always()
      run: |
        ccache --show-stats || true
        sccache --show-stats || true
      shell: bash

    # TODO cargo install; cargo fmt; cargo clippy?
    # do we call "cargo build --profile={{ matrix.build }}" manually or not needed?
