name: "cmake-build-and-test"
description: "Run CMake with CMakePreset.json to configure, build and test C/C++ source code."

inputs:
  ssh_key_input:
    description: "cf prepare/action.yml inputs.ssh_key_input"
    required: true

runs:
  using: "composite"
  steps:
    # TODO remove branch
    - uses: Interstellar-Network/gh-actions/prepare@add-cpp-ci
      with:
        ssh_key_input: ${{ inputs.ssh_key_input }}
        install_cmake_and_ninja: true

    # TODO remove branch
    - uses: Interstellar-Network/gh-actions/prepare_rust@add-cpp-ci
      with:
        toolchain_toolchain: stable

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

    # TODO cargo install; cargo fmt; cargo clippy?
    # do we call "cargo build --profile={{ matrix.build }}" manually or not needed?
