name: "prepare"
description: "Checkout, and optionally install C++ build prerequisites"

# We CAN NOT directly use secrets eg $\{\{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI \}\} here
# error: Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI
# So we instead use an input
# cf https://github.community/t/unrecognized-named-value-secrets-in-action-yml/207729
# and https://github.community/t/action-doesnt-understand-the-secrets-syntax-copied-from-the-documentation/16644/3
inputs:
  ssh_key_input:
    description: "SSH key of a MACHINE USER with access to all the org's repos"
    required: true
  # NOTE: https://github.com/actions/runner/issues/1483
  # For now all inputs are string, so compare with "true" in "if" statements
  install_cmake_and_ninja:
    description: "Install CMake and Ninja"
    required: false
    default: "false"
  install_sccache:
    description: "Install sccache"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v3
      # why is this not done automatically??
      # also for some reason we need to copy to another env var; INPUT_SSH_KEY_INPUT DOES NOT work
      env:
        SSH_KEY_ENV: ${{ inputs.ssh_key_input }}
      with:
        # recursive needed for api_circuits/api_garble b/c they have lib_circuits/lib_garble as deps, and those contains submodules
        submodules: "recursive"
        # SSH key of a MACHINE USER with access to all the org's repos
        # ssh-key: ${{ inputs.ssh_key_input }}  # Unrecognized named-value: 'inputs'
        ssh-key: ${{ env.SSH_KEY_ENV }}

    # "Using 'latest' branch, the most recent CMake and ninja are installed."
    # NOTE: make sure it matches the version, if any, in cmake-build-and-test/action.yml
    - uses: lukka/get-cmake@latest
      if: ${{ fromJSON(inputs.install_cmake_and_ninja) }}

    # hendrikmuhs/ccache-action: not doing anything really interesting,
    # and more importantly: ccache is version from APT which is old and deprecated
    # cf https://github.com/hendrikmuhs/ccache-action/blob/f3bbfde5b632a67f7bd66f4cbc0ff0cb1e87bc82/src/restore.ts#L43
    # and https://github.com/hendrikmuhs/ccache-action/blob/f3bbfde5b632a67f7bd66f4cbc0ff0cb1e87bc82/src/restore.ts#L15
    #
    # - name: sccache
    #   uses: hendrikmuhs/ccache-action@v1.2
    #   if: ${{ fromJSON(inputs.install_sccache) }}
    #   with:
    #     # NOTE: default is ccache, but that uses version from APT which is old and deprecated
    #     # TODO bench ccache vs sccache; if ccache is faster install latest manually? or from custom Docker?
    #     variant: sccache
    #     # TODO restore-keys, key, max-size?
    #
    - name: Install ccache custom prebuilt binary
      run: |
        wget https://github.com/Interstellar-Network/gh-actions/releases/download/ccache-4.6/ccache -O /usr/local/bin/ccache
        chmod +x /usr/local/bin/ccache
        ccache --show-config
      shell: bash

    - name: Setup env for ccache/sccache + internal CMakePresets.json
      run: |
        echo "ENV_CMAKE_C_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
        echo "ENV_CMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
      shell: bash

    # write a kind of compiler_id for the cache key at the next step
    - name: Set compilerid
      id: set-compilerid
      run: |
        echo "::set-output name=compilerid::$(realpath /usr/bin/cc)-$(cc -dumpversion)"
      shell: bash

    - name: ccache
      id: cache-ccache
      # using a fork that uploads even in case of failure
      # really useful for *_circuits b/c if a test fail after 20+mins of compilation it is wasteful to discard the compilation
      # uses: actions/cache@v3
      uses: pat-s/always-upload-cache@v3
      with:
        # cache_dir = /home/runner/.cache/ccache
        path: ~/.cache/ccache
        key: cache-${{ runner.os }}-${{ steps.set-compilerid.outputs.compilerid }}

    # MUST be after actions/cache@v3 else the stats are already empty
    - name: Reset ccache stats
      run: |
        ccache --zero
      shell: bash

    # TODO mold? or lld? there is a GH action for mold
