name: "rust-lint"
description: "Run CMake with CMakePreset.json to configure, build and test C/C++ source code."

inputs:
  fmt_args:
    description: "args passed to cargo fmt"
    required: false
    default: "-- --check"
  clippy_args:
    description: "args passed to cargo fmt"
    required: false
    default: "-- -D warnings"

runs:
  using: "composite"
  steps:
    - name: Run cargo fmt
      run: cargo fmt ${{ inputs.fmt_args }}
      shell: bash

    - name: Run cargo clippy
      run: cargo clippy ${{ inputs.clippy_args }}
      shell: bash

    # TODO move into separate action? ideally into a JS action "post" that setup ccache?
    - name: Print ccache/sccache stats
      # display stats even if tests failed
      if: always()
      run: |
        ccache --show-stats || true
        sccache --show-stats || true
      shell: bash

    # TODO cargo install
    # do we call "cargo build --profile={{ matrix.build }}" manually or not needed?
