name: "cmake-build-and-test"
description: "Run CMake with CMakePreset.json to configure, build and test C/C++ source code."

runs:
  using: "composite"
  steps:
    # TODO remove branch
    - uses: Interstellar-Network/gh-actions/prepare@add-cpp-ci
      with:
        install_cmake_and_ninja: true

    # TODO remove branch
    - uses: Interstellar-Network/gh-actions/prepare_rust@add-cpp-ci
      with:
        toolchain_toolchain: stable
        toolchain_profile: minimal
        toolchain_components: rustfmt, clippy

    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    # TODO cargo install
    # do we call "cargo build --profile={{ matrix.build }}" manually or not needed?
