name: 'cmake-build-and-test'
description: 'Run CMake with CMakePreset.json to configure, build and test C/C++ source code.'

# We CAN NOT directly use secrets eg $\{\{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI \}\} here
# error: Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI
# So we instead use an input
# cf https://github.community/t/unrecognized-named-value-secrets-in-action-yml/207729
# and https://github.community/t/action-doesnt-understand-the-secrets-syntax-copied-from-the-documentation/16644/3
inputs:
  ssh_key_input:
    description: "SSH key of a MACHINE USER with access to all the org's repos"
    required: true
  # same issue with 'githib' context:
  # "Unrecognized named-value: 'github'"
  cmake_lists_txt_path_input:
    description: "SSH key of a MACHINE USER with access to all the org's repos"
    required: true
    default: '${{ github.workspace }}/CMakeLists.txt'

on:
  push:

runs:
  using: "composite"
  steps:
    # DEBUG
    - run: echo "INPUT_SSH_KEY_INPUT = $INPUT_SSH_KEY_INPUT"
      shell: bash
    - run: echo "inputs.ssh_key_input = ${{ inputs.ssh_key_input }}"
      shell: bash
    - run: echo "INPUT_SSH_KEY_INPUT2 = $INPUT_SSH_KEY_INPUT2"
      shell: bash
      # why is this not done automatically??
      env:
        INPUT_SSH_KEY_INPUT2: ${{ inputs.ssh_key_input }}

    # https://github.com/actions/checkout
    - uses: actions/checkout@v3
      # why is this not done automatically??
      # also for some reason we need to copy to another env var; INPUT_SSH_KEY_INPUT DOES NOT work
      env:
        SSH_KEY_ENV: ${{ inputs.ssh_key_input }}
      with:
        # TODO recursive?
        submodules: 'true'
        # SSH key of a MACHINE USER with access to all the org's repos
        # ssh-key: ${{ inputs.ssh_key_input }}  # Unrecognized named-value: 'inputs'
        ssh-key: $SSH_KEY_ENV

    # "Using 'latest' branch, the most recent CMake and ninja are installed."
    - uses: lukka/get-cmake@latest

    # cf https://github.com/marketplace/actions/run-cmake
    # and https://github.com/lukka/CppCMakeVcpkgTemplate/blob/main/.github/workflows/hosted-ninja-vcpkg_submod.yml
    # TODO use Ninja Multi Config(and same when dev locally)
    - uses: lukka/run-cmake@v10
      # valid inputs are ['cmakeListsTxtPath', 'configurePreset',
      # 'buildPreset', 'testPreset', 'useShell', 'logCollectionRegExps',
      # 'configurePresetCmdString', 'buildPresetCmdString',
      # 'testPresetCmdString', 'runVcpkgEnvFormatString']
      with:
        cmakeListsTxtPath: '$INPUT_CMAKE_LISTS_TXT_PATH_INPUT'
        configurePreset: default
        buildPreset: default
        testPreset: default