name: "cmake-build-and-test"
description: "Run CMake with CMakePreset.json to configure, build and test C/C++ source code."

inputs:
  # same issue with 'github' context:
  # "Unrecognized named-value: 'github'"
  cmake_lists_txt_path_input:
    description: "SSH key of a MACHINE USER with access to all the org's repos"
    required: true
    default: "${{ github.workspace }}/CMakeLists.txt"

runs:
  using: "composite"
  steps:
    # TODO remove branch
    - uses: Interstellar-Network/gh-actions/prepare@add-cpp-ci
      with:
        install_cmake_and_ninja: true

    # cf https://github.com/marketplace/actions/run-cmake
    # and https://github.com/lukka/CppCMakeVcpkgTemplate/blob/main/.github/workflows/hosted-ninja-vcpkg_submod.yml
    # TODO use Ninja Multi Config(and same when dev locally)
    - uses: lukka/run-cmake@v10
      # valid inputs are ['cmakeListsTxtPath', 'configurePreset',
      # 'buildPreset', 'testPreset', 'useShell', 'logCollectionRegExps',
      # 'configurePresetCmdString', 'buildPresetCmdString',
      # 'testPresetCmdString', 'runVcpkgEnvFormatString']
      # why is this not done automatically??
      # also for some reason we need to copy to another env var; INPUT_SSH_KEY_INPUT DOES NOT work
      env:
        CMAKE_LISTS_TXT_PATH_ENV: ${{ inputs.cmake_lists_txt_path_input }}
      with:
        cmakeListsTxtPath: "${{ env.CMAKE_LISTS_TXT_PATH_ENV }}"
        configurePreset: "config-testing"
        buildPreset: "build-debug"
        testPreset: "test-debug"
